name: Deploy Website to EC2

on:
  push:
    branches: [ main ]  # Change "main" to your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can choose a different runner OS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main  # Or another SSH deployer action
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: /home/ubuntu/test  # Replace with the target directory on EC2

      # Additional steps (optional):
      # - name: Install dependencies (if needed)
      #   run:  'sudo apt update && sudo apt install -y npm i'

      - name: Build website (if needed)
        run:  'cd /home/ubuntu/test && npm run build'  # Replace with your build command

      - name: Restart web server (if needed)
        run:  'sudo systemctl restart nginx.service'  # Replace with your service name
